SET (TOOL_CHAIN_ROOT $ENV{TOOLCHAIN})
SET (TOOL_CHAIN_BIN_DIR ${TOOL_CHAIN_ROOT}/bin)
SET (TOOL_CHAIN_LIBC_DIR ${TOOL_CHAIN_ROOT}/sysroot/usr/lib)
SET (TOOL_CHAIN_LIB_DIR ${TOOL_CHAIN_ROOT}/sysroot/usr/lib)
SET (TOOL_CHAIN_INC_DIR ${TOOL_CHAIN_LIBC_DIR}/sysroot/usr/include)


SET(CMAKE_SYSTEM_NAME VoCore2)
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_SYSTEM_PROCESSOR mips)



SET(CMAKE_C_COMPILER ${TOOL_CHAIN_BIN_DIR}/arm-linux-androideabi-gcc)
SET(CMAKE_CXX_COMPILER ${TOOL_CHAIN_BIN_DIR}/arm-linux-androideabi-g++)
#SET(CMAKE_C_FLAGS "-isystem ${TOOL_CHAIN_INC_DIR}")
#SET(CMAKE_CXX_FLAGS "-isystem ${TOOL_CHAIN_INC_DIR}")

SET (CMAKE_EXE_LINKER_FLAGS -static)
SET (CMAKE_FIND_ROOT_PATH ${TOOL_CHAIN_ROOT})

#SET(LINK_FLAGS -L${TOOL_CHAIN_LIB_DIR})
#set(CMAKE_MODULE_LINKER_FLAGS ${LINK_FLAGS})
#set(CMAKE_SHARED_LINKER_FLAGS ${LINK_FLAGS})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
#set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH )
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH )
